/* GUIONES EDITABLES — Unidad 5 · Versión V21 ampliada */
window.GUIONES_U5 = {
  s1: `
Presentamos la Unidad 5, Fluidos. La idea central es pasar de las fuerzas aplicadas sobre la materia al comportamiento de líquidos, gases, productos viscosos y también sólidos granulares. No comenzamos directamente con Bernoulli ni con hidrostática: primero recuperamos fuerza, área, esfuerzo y deformación, porque esas ideas permiten entender qué distingue a un sólido de un fluido. Luego avanzamos hacia densidad, presión, presión hidrostática, Pascal, Arquímedes, caudal, continuidad, Bernoulli y fluidos reales. En todo momento el objetivo será interpretar situaciones de Tecnología de Alimentos: tanques, bombas, tuberías, válvulas, llenado, mezclado, intercambiadores, sistemas CIP, productos viscosos y tolvas.
`,
  s2: `
El recorrido de la unidad se organiza en seis bloques. Primero, esfuerzo y deformación: fuerza distribuida sobre un área y respuesta del material. Segundo, sólidos, fluidos y viscosidad: la diferencia se construye a partir del comportamiento frente al esfuerzo cortante. Tercero, densidad y presión: dos magnitudes básicas para describir fluidos. Cuarto, hidrostática, Pascal y Arquímedes: fluidos en reposo, transmisión de presión y empuje. Quinto, caudal, continuidad y Bernoulli: fluidos en movimiento y balance de energía ideal. Sexto, fluidos reales y aplicaciones: viscosidad, pérdidas de carga, accesorios, bombas y productos alimentarios reales. La idea conductora es usar modelos simples, pero siempre declarando sus límites.
`,
  s3: `
Los objetivos se presentan como acciones que el estudiante debería poder realizar. Primero, comprender: distinguir esfuerzo normal, esfuerzo cortante, deformación, viscosidad y comportamiento reológico. Segundo, calcular: densidad, peso específico, presión, presión hidrostática, caudal y velocidad media. Tercero, interpretar: leer físicamente la relación entre presión, velocidad y altura en un fluido ideal. Cuarto, aplicar: conectar ecuaciones con tanques, cañerías, bombas, válvulas, llenado, mezclado y limpieza. Quinto, reconocer límites: saber cuándo Bernoulli ideal no alcanza, cuándo la viscosidad domina y cuándo el producto alimentario no puede tratarse como fluido newtoniano simple.
`,
  s4: `
En esta filmina incorporamos el video del ensayo de tracción porque permite observar experimentalmente la respuesta de un sólido frente a una carga creciente. El procedimiento comienza con una probeta de geometría conocida, sujeta por mordazas. La máquina aplica una fuerza axial de tracción y registra simultáneamente fuerza y alargamiento. Al inicio aparece una zona elástica: la deformación es aproximadamente proporcional al esfuerzo y, si se descarga, el material tiende a recuperar su forma. Luego puede aparecer el límite de proporcionalidad y la zona de fluencia o cedencia, donde comienza la deformación permanente. Después se desarrolla deformación plástica: el material sigue alargándose aunque no recupere su forma inicial. En muchos metales aparece endurecimiento por deformación hasta alcanzar una carga máxima, asociada con la resistencia última a la tracción. Luego puede observarse estricción, una reducción local de la sección. Finalmente ocurre la rotura. La tensión de rotura se obtiene relacionando la fuerza de rotura con el área de referencia de la probeta. Este video nos sirve como contraste: un sólido puede sostener esfuerzos y acumular una deformación finita; un fluido, frente a un esfuerzo cortante sostenido, no alcanza una deformación fija, sino que continúa deformándose.
`,
  s5: `
Esta imagen resume el punto de partida conceptual. El esfuerzo normal se produce cuando la fuerza actúa perpendicularmente a una superficie; se calcula como fuerza normal dividida por el área. El esfuerzo cortante aparece cuando la fuerza es paralela o tangencial a la superficie; allí el efecto principal es el cambio de forma. La deformación por corte se representa con gamma y se aproxima como desplazamiento lateral dividido por la altura del elemento. La idea importante es que una fuerza no se interpreta sola: debemos conocer su dirección, el área sobre la que actúa y la respuesta del material. Esta distinción será la base para conectar esfuerzo normal con presión, y esfuerzo cortante con viscosidad.
`,
  s6: `
La deformación puede analizarse en una, dos o tres dimensiones. En una dimensión, lo más relevante es el cambio de longitud: por ejemplo, una barra que se estira o se comprime. En dos dimensiones, una lámina puede modificar su área, como una masa durante el laminado: aumenta en una dirección, cambia en otra y puede disminuir su espesor. En tres dimensiones aparece el cambio de volumen, descrito mediante una deformación volumétrica. Esta distinción es útil porque los fluidos reales pueden cambiar de forma con facilidad, pero los líquidos suelen cambiar muy poco su volumen bajo presiones moderadas. Por eso, en muchos problemas de alimentos y de transporte en tuberías, adoptamos el modelo de fluido incompresible, es decir, densidad prácticamente constante.
`,
  s7: `
La deformación por corte aparece cuando distintas capas de un material tienden a desplazarse paralelamente unas respecto de otras. Si la base de un bloque queda fija y la cara superior se desplaza, el rectángulo inicial se transforma en un paralelogramo. La magnitud gamma mide esa deformación relativa. En un sólido elástico, el esfuerzo cortante puede equilibrarse con una deformación finita; por eso se introduce el módulo de corte. Esta idea es clave: el sólido resiste el corte deformándose hasta una configuración. En un fluido, en cambio, el esfuerzo cortante sostenido produce movimiento continuo entre capas. Así pasamos de deformación geométrica a flujo.
`,
  s8: `
La comparación visual entre sólido ideal y fluido condensa el puente conceptual de la unidad. En el sólido ideal, el esfuerzo cortante genera una deformación limitada; si el material está dentro del régimen elástico, esa deformación puede estabilizarse. En el fluido, el mismo tipo de esfuerzo no genera una deformación fija, sino un proceso continuo: las capas se deslizan, aparecen velocidades distintas y el material fluye. La diferencia clave es entonces temporal: en el sólido interesa cuánto se deformó; en el fluido interesa además qué tan rápido se está deformando. Por eso aparecerá la rapidez de deformación y, con ella, la viscosidad.
`,
  s9: `
La definición mecánica de fluido se formula a partir de la respuesta al esfuerzo cortante. Un sólido puede sostener un esfuerzo cortante mediante una deformación estática o limitada. Un fluido no sostiene un esfuerzo cortante estático: si el esfuerzo tangencial se mantiene, el material continúa deformándose. Esta afirmación permite entender por qué en un fluido en reposo las fuerzas relevantes sobre superficies son normales, no tangenciales. También explica por qué algunos alimentos pueden comportarse de manera ambigua: pueden parecer sólidos en reposo, pero fluir al superar un esfuerzo mínimo. Esa situación anticipa los fluidos no newtonianos y los materiales con esfuerzo de cedencia.
`,
  s10: `
El origen macroscópico de la viscosidad se entiende observando capas de fluido. Si una placa superior arrastra el fluido y una placa inferior permanece fija, la velocidad no es igual en todo el espesor. Cerca de la placa móvil la velocidad es mayor; cerca de la placa fija es menor. El gradiente de velocidad, dv sobre dy, describe esa variación espacial. Esa diferencia de velocidad entre capas equivale a una rapidez de deformación por corte. La viscosidad mide la resistencia interna a ese deslizamiento relativo. En una planta alimentaria, esta resistencia se expresa como mayor demanda de bombeo, dificultad de mezclado, menor velocidad de llenado o mayor pérdida de presión.
`,
  s11: `
La ley de Newton de la viscosidad establece que, para un fluido newtoniano, el esfuerzo cortante tau es proporcional al gradiente de velocidad o rapidez de deformación. La constante de proporcionalidad es la viscosidad dinámica mu. Si mu es alta, se necesita mayor esfuerzo para producir la misma deformación; si mu es baja, el fluido se mueve con mayor facilidad. Esta ecuación debe leerse físicamente: no es sólo una fórmula, sino una relación entre fuerza tangencial por área y deformación continua entre capas. La viscosidad dinámica se mide en pascal segundo, y la viscosidad cinemática se obtiene dividiendo mu por la densidad.
`,
  s12: `
La viscosidad depende fuertemente de las condiciones de proceso. En muchos líquidos, al aumentar la temperatura, la viscosidad disminuye; por eso aceites, jarabes o miel fluyen mejor cuando se calientan. La composición también es importante: sólidos disueltos, partículas suspendidas, aire incorporado y concentración modifican la resistencia al flujo. En productos alimentarios estructurados, la rapidez de deformación también cambia la viscosidad aparente. Por eso no alcanza con decir que un producto tiene cierta viscosidad: se debe indicar temperatura, método de medición, estado del producto, velocidad de deformación e historial de agitación o bombeo.
`,
  s13: `
Los fluidos newtonianos y no newtonianos se distinguen por la relación entre esfuerzo cortante y rapidez de deformación. En un fluido newtoniano, la relación es lineal y la viscosidad permanece aproximadamente constante. El agua y algunos aceites simples pueden modelarse de este modo en muchas condiciones. En un fluido pseudoplástico, la viscosidad aparente disminuye al aumentar la rapidez de deformación; esto ocurre en yogures, salsas y purés. En un dilatante, la resistencia aumenta cuando aumenta la deformación. En un plástico de Bingham, primero debe superarse un esfuerzo de cedencia. Estas categorías ayudan a interpretar bombeo, mezclado, dosificación, llenado y textura.
`,
  s14: `
Esta síntesis visual cierra el bloque de reología básica. El eje vertical representa esfuerzo cortante y el eje horizontal rapidez de deformación. La recta newtoniana indica viscosidad constante. La curva pseudoplástica se aplana: el producto se adelgaza con el corte. La curva dilatante se empina: el producto se espesa con la deformación. El modelo plástico de Bingham incluye un esfuerzo inicial de cedencia antes de fluir. La parte inferior conecta estas curvas con ejemplos alimentarios y con operaciones. La conclusión es directa: conocer el tipo de fluido permite prever caídas de presión, potencia de bombeo, facilidad de mezcla y comportamiento en boquillas o válvulas.
`,
  s15: `
Los ensayos aplicados sobre alimentos permiten medir respuestas mecánicas que se relacionan con textura, consistencia y procesamiento. En compresión se estima firmeza o dureza. En punción se mide resistencia local, por ejemplo en una fruta, un gel o un queso. En corte se evalúa la fuerza necesaria para seccionar un producto fibroso o estructurado. En TPA, o análisis de perfil de textura, se comprime dos veces la muestra para obtener dureza, elasticidad, cohesividad, gomosidad y masticabilidad. En extrusión o back extrusion se fuerza el material a fluir, lo que ayuda a comparar consistencia y viscosidad aparente. En adhesividad se mide la fuerza necesaria para despegar la sonda. Estos ensayos vinculan propiedades físicas con aceptación sensorial y con comportamiento en planta.
`,
  s16: `
La densidad relaciona masa y volumen. Es una propiedad intensiva: no depende de cuánta muestra tomemos, aunque sí puede variar con temperatura, presión y composición. En líquidos alimentarios, la densidad permite convertir volumen almacenado en masa de producto; esto es importante en tanques, dosificación y balances de materia. También aparece directamente en hidrostática, porque la presión debida al peso de una columna de líquido depende de rho. En hidrodinámica, la densidad permite pasar de caudal volumétrico a caudal másico. Por eso es una magnitud puente entre geometría, masa, peso, presión y transporte.
`,
  s17: `
La tabla de densidades cumple una función de escala. Los gases tienen densidades mucho menores que líquidos y sólidos; por eso aire y helio aparecen con valores muy bajos. El agua se usa como referencia cercana a mil kilogramos por metro cúbico. El aceite tiene menor densidad que el agua, por eso tiende a flotar sobre ella. La melaza aparece con una densidad mayor, coherente con su alta concentración de sólidos. Los sólidos como aluminio o hierro tienen densidades mucho más altas. En alimentos, la densidad real depende de composición, temperatura, aire incorporado, sólidos disueltos y estructura del producto.
`,
  s18: `
El peso específico no es lo mismo que la densidad. La densidad mide masa por volumen y se expresa en kilogramos por metro cúbico. El peso específico mide peso por volumen y se expresa en newtons por metro cúbico; por eso se obtiene multiplicando densidad por gravedad. La densidad relativa compara una sustancia con una referencia, generalmente agua. Si la densidad relativa es menor que uno, el material tiende a ser menos denso que el agua; si es mayor que uno, es más denso. Esta distinción evita confundir masa, peso, densidad, peso específico y flotación.
`,
  s19: `
La presión se define como fuerza perpendicular distribuida sobre un área. Si la misma fuerza actúa sobre un área pequeña, la presión es mayor; si actúa sobre un área grande, la presión es menor. Por eso la presión no es simplemente fuerza: incluye cómo esa fuerza se reparte. En un fluido en reposo, las fuerzas que el fluido ejerce sobre una superficie son normales a esa superficie. Esta idea conecta con el esfuerzo normal que estudiamos al comienzo de la unidad. La unidad del Sistema Internacional es el pascal, equivalente a un newton por metro cuadrado.
`,
  s20: `
La imagen de definición de presión resume tres aspectos. Primero, la expresión P igual a fuerza perpendicular dividida por área. Segundo, la representación gráfica: una fuerza normal actuando sobre una superficie de contacto. Tercero, el efecto del área: para una misma fuerza, un área menor produce mayor presión y un área mayor produce menor presión. También se muestra una tabla de unidades, porque en la práctica aparecen pascales, kilopascales, bar, atmósferas, milímetros de mercurio y psi. Es importante poder reconocerlas y convertirlas, especialmente al leer instrumentos, catálogos o manuales técnicos.
`,
  s21: `
La presión en un punto de un fluido se interpreta como una magnitud escalar. La presión no tiene una dirección propia, aunque la fuerza que produce sobre una superficie sí tiene dirección, porque siempre actúa perpendicularmente a esa superficie. En un fluido en reposo no puede mantenerse un esfuerzo cortante sostenido; por eso las fuerzas tangenciales desaparecen del modelo hidrostático. La presión puede variar de un punto a otro, especialmente con la profundidad. Esta idea permite pasar de la definición general de presión a la ecuación hidrostática.
`,
  s22: `
Para deducir la presión hidrostática analizamos el equilibrio vertical de un pequeño elemento de fluido. Sobre la cara superior actúa una fuerza hacia abajo, sobre la cara inferior una fuerza hacia arriba, y además actúa el peso del elemento. Como el fluido está en reposo, la suma de fuerzas verticales debe ser cero. Primero escribimos el equilibrio con fuerzas: fuerza dos menos fuerza uno menos peso igual a cero. Luego usamos la relación fuerza igual presión por área, y el peso como rho por g por volumen. Si el volumen del elemento es área por diferencia de alturas, se obtiene que la presión inferior es igual a la presión superior más rho g por la diferencia de profundidad. Así aparece la ley hidrostática.
`,
  s23: `
La ecuación hidrostática expresa que la presión aumenta con la profundidad. Entre dos puntos separados verticalmente, la diferencia de presión es rho g por la diferencia de altura. Si tomamos como referencia la superficie libre, donde la presión es P cero, la presión a profundidad h es P igual a P cero más rho g h. Esta fórmula no dice que el volumen total del tanque sea lo importante; lo importante es la profundidad del punto, la densidad del líquido, la gravedad y la presión aplicada en la superficie. A igual profundidad, en un fluido conectado y en reposo, la presión es la misma.
`,
  s24: `
Esta filmina ayuda a prevenir errores. La presión hidrostática depende de densidad, gravedad, profundidad y presión superficial. No depende directamente de la forma del recipiente, del volumen total almacenado ni del área de la base cuando comparamos puntos a igual profundidad. En un tanque industrial, esto significa que una columna alta de líquido puede generar una presión importante en el fondo aunque el tanque no sea muy ancho. También explica por qué los sensores de presión pueden utilizarse para inferir nivel, siempre que se conozca la densidad del producto y las condiciones de operación.
`,
  s25: `
La presión absoluta se mide respecto del vacío. La presión manométrica se mide respecto de la presión atmosférica. La presión atmosférica es la ejercida por la columna de aire sobre nosotros y sobre los equipos. La relación entre ellas es presión absoluta igual a presión manométrica más presión atmosférica. Un manómetro que marca cero no indica vacío: indica que la presión del sistema es igual a la atmosférica. Esta diferencia es importante al leer sensores, bombas, tanques y recipientes presurizados. En industria es frecuente trabajar con presión manométrica, pero los cálculos termodinámicos suelen requerir presión absoluta.
`,
  s26: `
El principio de Pascal establece que una variación de presión aplicada a un fluido confinado se transmite a todos los puntos del fluido. En una prensa hidráulica, esto permite que una fuerza pequeña aplicada sobre un pistón de área reducida genere una fuerza mayor sobre otro pistón de área mayor. Lo que se transmite no es la fuerza, sino la presión. No hay creación de energía: la ganancia de fuerza se compensa con menor desplazamiento del pistón grande. Esta idea aparece en equipos hidráulicos, sistemas de accionamiento, prensas y mecanismos donde interesa multiplicar fuerza controlando áreas.
`,
  s27: `
El principio de Arquímedes indica que un cuerpo total o parcialmente sumergido recibe un empuje igual al peso del fluido desplazado. Ese empuje surge porque la presión aumenta con la profundidad: la fuerza sobre la parte inferior del cuerpo es mayor que sobre la parte superior. Por eso el resultado neto es una fuerza hacia arriba. El empuje depende de la densidad del fluido y del volumen desplazado, no directamente de la masa del objeto. Esta idea explica flotación, hundimiento, separación por densidad y mediciones con hidrómetros.
`,
  s28: `
La flotación se obtiene comparando peso y empuje. Si el peso es mayor que el empuje máximo posible, el cuerpo se hunde. Si el cuerpo puede desplazar suficiente fluido para que el empuje iguale a su peso, flota. En equilibrio, el empuje es igual al peso. La fracción sumergida depende de la relación entre la densidad del objeto y la densidad del fluido. En Tecnología de Alimentos esta idea puede relacionarse con separación de materias primas, control de calidad, concentración de soluciones y comportamiento de partículas o gotas en líquidos.
`,
  s29: `
Al pasar de hidrostática a hidrodinámica dejamos de estudiar fluidos en reposo y empezamos a describir fluidos en movimiento. Para eso usamos el campo de velocidades: la velocidad puede cambiar de un punto a otro y también con el tiempo. Si en cada punto las variables permanecen constantes en el tiempo, hablamos de flujo estacionario. Las líneas de corriente indican la dirección del movimiento. En flujo laminar las capas se desplazan de forma ordenada; en turbulento aparecen fluctuaciones y remolinos. Para construir continuidad y Bernoulli comenzaremos con modelos simplificados.
`,
  s30: `
El caudal volumétrico es el volumen que atraviesa una sección por unidad de tiempo. Si la sección tiene área A y la velocidad media es v, entonces Q es igual a A por v. Esta ecuación conecta geometría de la tubería y movimiento del fluido. El caudal puede expresarse en metros cúbicos por segundo, litros por minuto o metros cúbicos por hora. El caudal másico se obtiene multiplicando por la densidad: masa por unidad de tiempo. Esta magnitud es central en balances de materia, dosificación, producción, llenado y control de líneas de proceso.
`,
  s31: `
La continuidad es conservación de masa aplicada a un fluido en movimiento. Si no hay acumulación en un tramo de tubería, la masa que entra por unidad de tiempo debe ser igual a la masa que sale. La forma general incluye densidad, área y velocidad en cada sección. Si el fluido es incompresible, la densidad se cancela y queda A uno v uno igual a A dos v dos. Esto explica por qué la velocidad aumenta en un estrechamiento: el mismo caudal debe pasar por un área menor. No se crea fluido; se redistribuye la velocidad.
`,
  s32: `
El apoyo visual de continuidad muestra una tubería con una sección ancha y otra estrecha. En la sección ancha, para un mismo caudal, la velocidad media puede ser menor. En la sección estrecha, la velocidad debe aumentar. Esta idea aparece en boquillas de llenado, reducciones, tuberías sanitarias, medidores de caudal y zonas de aceleración del producto. También ayuda a separar dos conceptos: caudal total y velocidad local. Pueden cambiar las velocidades en distintas zonas, pero mantenerse el mismo caudal si no hay acumulación.
`,
  s33: `
Bernoulli es un balance de energía mecánica por unidad de volumen para un fluido ideal. El término P representa energía asociada a presión. El término un medio rho v cuadrado representa energía cinética por unidad de volumen. El término rho g h representa energía potencial gravitatoria por unidad de volumen. Si el fluido ideal se mueve en régimen estacionario y sin pérdidas apreciables, la suma de esos términos se conserva a lo largo de una línea de corriente. Esta lectura permite entender intercambios: más velocidad puede implicar menor presión, y mayor altura implica mayor energía potencial.
`,
  s34: `
Esta imagen organiza los términos de Bernoulli. Los tres términos tienen las mismas unidades, pascales, equivalentes a energía por unidad de volumen. También puede escribirse una forma en altura de energía, dividiendo por rho g. Esa forma permite hablar de altura de presión, altura cinética y altura geométrica. Antes de aplicar Bernoulli debemos verificar sus hipótesis: flujo estacionario, fluido aproximadamente incompresible, análisis sobre una línea de corriente, sin bombas entre los puntos y pérdidas despreciables. Si esas condiciones no se cumplen, la ecuación debe modificarse.
`,
  s35: `
Venturi y Torricelli son aplicaciones clásicas de continuidad y Bernoulli. En un Venturi, al reducirse el área, la continuidad exige que la velocidad aumente. En un conducto horizontal ideal, ese aumento de velocidad se acompaña de una disminución de presión estática. Por eso la diferencia de presión puede usarse para estimar caudal. Torricelli se obtiene al analizar la descarga de un depósito abierto: la velocidad de salida depende de la altura de líquido sobre el orificio. En la práctica, ambos resultados requieren correcciones por viscosidad, pérdidas y geometría real.
`,
  s36: `
En fluidos reales aparecen efectos que Bernoulli ideal no incorpora directamente. La condición de no deslizamiento indica que el fluido en contacto con una pared fija tiene velocidad casi nula respecto de esa pared. Por eso el perfil de velocidades no es uniforme. Además, la viscosidad disipa energía mecánica, de modo que la presión disminuye en el sentido del flujo incluso en una tubería horizontal. A eso se suman pérdidas localizadas en codos, válvulas, filtros, reducciones y accesorios. Para productos viscosos, estas pérdidas pueden dominar el diseño de la línea.
`,
  s37: `
La comparación entre fluido ideal y fluido real permite elegir el nivel de modelo. El fluido ideal es útil para entender tendencias entre presión, velocidad y altura. El fluido real incorpora viscosidad, paredes, turbulencia, accesorios y pérdidas de carga. En Tecnología de Alimentos esto es esencial: una línea que funciona con agua puede no funcionar igual con jarabe, yogur, salsa o puré. La viscosidad puede variar con temperatura, concentración y rapidez de deformación. Por eso el análisis real exige preguntar qué producto circula, a qué temperatura, por qué diámetro y con qué caudal.
`,
  s38: `
Esta síntesis visual integra el bloque de hidrodinámica. Primero aparece caudal: volumen o masa por tiempo. Después continuidad: conservación de masa. Luego Bernoulli: intercambio ideal entre presión, velocidad y altura. Venturi y Torricelli muestran aplicaciones. Finalmente, los fluidos reales agregan pérdidas, viscosidad y accesorios. La lectura recomendada es escalonada: usar continuidad para conservar masa, Bernoulli para interpretar energía ideal, y pérdidas para acercarse a la instalación real. En planta, los tres niveles suelen combinarse.
`,
  s39: `
Los sólidos granulares amplían la unidad porque muchos alimentos no se manejan como líquidos, sino como partículas. Harina, azúcar, cacao, sal, almidón, leche en polvo, cereales o mezclas secas pueden fluir colectivamente, pero no se comportan como un líquido ideal. Aparecen puentes, chimeneas, segregación, compactación y descarga irregular. Para analizarlos se usan magnitudes específicas como densidad aparente, porosidad y ángulo de reposo. El diseño de tolvas y alimentadores depende tanto del material como de la geometría del equipo.
`,
  s40: `
La densidad aparente es masa dividida por el volumen total ocupado por el lecho de partículas, incluyendo huecos. Por eso no coincide necesariamente con la densidad del sólido que forma cada partícula. La porosidad mide la fracción de volumen ocupada por esos huecos. El ángulo de reposo indica cómo se apila un material granular: un ángulo mayor suele asociarse con peor fluidez o mayor cohesión. Estas propiedades cambian con humedad, granulometría, compactación y vibración. En alimentos secos, pequeños cambios de humedad pueden alterar fuertemente el flujo.
`,
  s41: `
En tolvas se distinguen dos patrones principales. En flujo másico, prácticamente todo el material se mueve durante la descarga. Esto favorece renovación uniforme, reduce zonas muertas y ayuda a mantener trazabilidad. En flujo en embudo, se descarga primero una zona central, mientras parte del material queda detenido en las paredes. Esto puede generar segregación, envejecimiento local, compactación y descarga irregular. La diferencia depende del ángulo de la tolva, rugosidad de paredes, tamaño de salida y propiedades del polvo. Para alimentos, esto afecta dosificación, limpieza e inocuidad.
`,
  s42: `
Los problemas frecuentes en tolvas muestran que la gravedad no siempre alcanza para descargar un polvo. El puente o arco ocurre cuando el material forma una estructura estable sobre la salida. El ratholing o chimenea aparece cuando sólo fluye un canal central y queda material detenido alrededor. La segregación separa partículas por tamaño o densidad, alterando la formulación. La compactación aumenta la resistencia al flujo. Estos problemas dependen de humedad, cohesión, granulometría, tiempo de almacenamiento, vibración, geometría de descarga y material de construcción de la tolva.
`,
  s43: `
En una línea alimentaria real todos los conceptos se combinan. Un tanque genera presión hidrostática según nivel y densidad. Una bomba aporta energía para sostener caudal y compensar pérdidas. Las tuberías imponen continuidad entre área, velocidad y caudal. Las válvulas y accesorios agregan pérdidas localizadas. Los intercambiadores modifican temperatura y, por tanto, viscosidad. Un sistema CIP requiere velocidad y régimen adecuados para limpiar. Si el producto es granular, la tolva agrega problemas de descarga y segregación. La unidad debe leerse como una caja integrada de herramientas.
`,
  s44: `
Los errores frecuentes ayudan a revisar el aprendizaje. Densidad no es peso específico. Presión no es fuerza, sino fuerza dividida por área. Presión manométrica cero no significa vacío. La presión hidrostática no depende directamente de la forma del recipiente, sino de profundidad, densidad y gravedad. Bernoulli ideal no debe aplicarse sin revisar hipótesis. Continuidad no dice que el estrechamiento cree caudal; dice que cambia la velocidad. Y muchos alimentos no son newtonianos: su viscosidad aparente puede variar con temperatura, composición y rapidez de deformación.
`,
  s45: `
El cierre conecta los modelos centrales. El esfuerzo normal relaciona fuerza perpendicular y área. El esfuerzo cortante abre la puerta a deformación por corte y viscosidad. La densidad conecta masa, volumen, peso específico y presión hidrostática. La presión permite estudiar fluidos en reposo y fuerzas sobre superficies. La hidrostática explica la variación con profundidad. Pascal describe transmisión de presión; Arquímedes, empuje. El caudal y la continuidad expresan conservación de masa. Bernoulli relaciona presión, velocidad y altura en un fluido ideal. Los fluidos reales agregan pérdidas, y los polvos requieren modelos complementarios. Todo apunta a interpretar almacenamiento, transporte, bombeo, llenado, mezclado y manejo de productos alimentarios.
`,
};
